# Site settings
title: Johnsonmawuli
description: blog
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Johnson Mawuli Tsimese
user_description: I am currently masters student studying Business Analytics at Saint Marys University. I have a backgroud in Insurance, Statistics, Mathematics, Accounting since I did my bachelors in Actuarial Science. I currently have internship experience from Phoenix Insurance, Jem Intercontinental etc. I love to compile and edit videos as a hobby. I have worked made videos (reels) for brands too. My goal is to succeed in every challenging field I find myself in. 
user_title: Analyst; Vlogger
email: tsimesejohnson@gmail.com
instagram_username: mawulijt
github_username:  johnsonmawuli


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
