# Site settings
title: Johnsonmawuli
description: blog
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Johnson Mawuli Tsimese
user_description: This page contains everything you need to know about me. Thanks for your time tho! 
user_title: Analyst; Blogger
email: tsimesejohnson@gmail.com
instagram_username: mawulijt
github_username:  johnsonmawuli


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
